spring:
  profiles:
    active:
      -dev
---
server:
  port: 8201
eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka/
spring:
  application:
    name: microservicecloud-config-client
---
server:
  port: 8202
eureka:
  client:
    service-url:
      defaultZone: http://eureka-test.com:7001/eureka/
spring:
  application:
    name: microservicecloud-config-client